# Generated by Django 2.2.3 on 2019-07-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190703_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
