# Generated by Django 2.2.3 on 2019-07-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
