# Generated by Django 2.2.3 on 2019-07-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
