# Generated by Django 2.2.3 on 2019-07-04 14:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='page_type',
            field=models.CharField(choices=[('pa', 'page'), ('ch', 'chapter')], default='pa', max_length=2),
        ),
    ]
