# Generated by Django 2.2.3 on 2019-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190704_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='page_type',
            field=models.CharField(choices=[('pa', 'page'), ('ch', 'chapter')], default='ch', max_length=2),
        ),
    ]
