# Generated by Django 2.2.4 on 2019-08-21 16:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190821_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
