# Generated by Django 2.2.4 on 2019-08-21 17:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190821_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
