# Generated by Django 2.2.4 on 2019-08-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190821_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter', 'pk'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['pk'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='book',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
