# Generated by Django 2.2.4 on 2019-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190821_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['number', 'pk'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['number', 'pk'], 'verbose_name': 'PageContent', 'verbose_name_plural': 'PageContents'},
        ),
    ]
