# Generated by Django 2.2.3 on 2019-09-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190823_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['pk'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AddField(
            model_name='book',
            name='chapter_start_in',
            field=models.IntegerField(default=1),
        ),
    ]
